### ISSUE TITLE
Code wrong

### ISSUE THREAD

**Issue by theeal** [elviswolcott/onion-puns#1]
At line 46 it's two space and not a tab.
please update

**Comment by elviswolcott** [comment]
Thanks for pointing that out! I've fixed it for you.

It looks like you're new to GitHub. so I figured I'd give you a quick how-to so you can learn how to make contributions like this in the future (if you're already familiar with pull requests fell free to ignore this).

When you see an issue like this in a repository and you now how to fix it yourself.

First, you need a copy of the code that you can edit. 
Either:
1. Create a fork of the repository
    * https://help.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository
-or-
1. Create a branch of the repository (some repositories might not allow you to do this)
    * https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository#creating-a-branch

Then, you can make the changes and commit them to your fork/branch. Obviously, you want to get this code back into the main repository so other people can use it. A good first step is creating an issue (as you did). This way, the maintainers can comment in case they have a fix planned. You can add a link to your fork/branch so that others can find it if they are searching for a fix to the issue.

Next, create a merge request. A merge request is just you asking the maintainers of the repository to integrate the fix you wrote.
    * https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Most likely, the maintainers will merge your changes and they will be there for everyone. If they don't (maybe they have a fix planned themselves or they are inactive), the issue and merge request will still make it easy for others to find your fix through searching or looking at the repository.

Happy coding!
